wslu: style unification and speed up

diff --git a/src/wslu-header b/src/wslu-header
--- a/src/wslu-header
+++ b/src/wslu-header
@@ -35,7 +35,7 @@ if [ "$1" == "--verbose" ]; then
 fi
 
 # checking interopability
-grep enabled /proc/sys/fs/binfmt_misc/WSLInterop >/dev/null || (echo "WSL Interopability is disabled. Please enable it before using WSL."; exit 1)
+grep enabled /proc/sys/fs/binfmt_misc/WSLInterop >/dev/null || (echo -e "\e[31m\033[1m[error] WSL Interopability is disabled. Please enable it before using WSL.\033(B\033[m"; exit 1)
 
 # variables
 ## color
