proper exit code for invalid input

diff --git a/src/wslupath b/src/wslupath
--- a/src/wslupath
+++ b/src/wslupath
@@ -48,7 +48,8 @@ function general_converter
 	elif [[ $target =~ ^\/mnt\/[A-Za-z](\/[^:/]+)*(\/)?$ ]]; then
 		p="$(path_win $@)"
 	else
-		p="${error} No path form detected: $@."
+		echo "${error} No proper path form detected: $@."
+		exit 20
 	fi
 	echo $p
 }
